services:
    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category}

    app.admin.suggestion:
        class: AppBundle\Admin\SuggestionAdmin
        arguments: [~, AppBundle\Entity\Suggestion, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Suggestion}

    app.admin.mailing:
        class: AppBundle\Admin\MailingAdmin
        arguments: [~, AppBundle\Entity\Mailing, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Mailing}
